app:
  values:
    api:
      giga-chat:
        base-url:
          auth: "https://ngw.devices.sberbank.ru:9443"
          chat: "https://gigachat.devices.sberbank.ru"
        chat-settings:
          scope: "GIGACHAT_API_PERS"
        auth-key: "ZjBjZmU2Y2EtMTUwYi00ZWIzLWE3MzEtOGE2OGRkNjljYzNkOjU0ZDIzOTM1LTlmMDMtNDg0Ni1iNmEyLTQxZTc2NGRhYTA3OA=="



spring:
  application:
    name: IdeaThesis
